{% set name = "libraw" %}
{% set version = "0.20.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LibRaw/LibRaw/archive/{{ version }}.tar.gz
  sha256: 02df7d403b34602b769bb38e5bf7d4258e075eeefbe980b6832e6e1491989d60

build:
  skip: true  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - automake
    - libtool
    - pkg-config
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - zlib
    - lcms2
    - jpeg
    # - llvm-openmp  # [osx]
    - libgomp      # [linux]
  run:
    - {{ pin_compatible('lcms2', max_pin='x.x') }}

test:
  commands:
#    - raw-identify -h
#    - simple_dcraw -h
    - test -f ${PREFIX}/include/libraw/libraw.h  # [unix]
    - test -f ${PREFIX}/lib/libraw${SHLIB_EXT}  # [unix]

about:
  home: http://www.libraw.org/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.LGPL
  description: |
    LibRaw is a library for reading RAW files from digital photo cameras
    (CRW/CR2, NEF, RAF, DNG, MOS, KDC, DCR, etc, virtually all RAW formats are supported).
  summary: Library for reading and processing of RAW digicam images.

extra:
  recipe-maintainers:
    - wolfv
